base_url = "https://jianghaiyina.com/"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "Lirui's Blog"
even_menu = [
    {url = "/", name = "Home"},
    {url = "/tags/top/", name = "Top"},
    {url = "/tags/", name = "Tags"},
    {url = "/issue-1/", name = "About"},
    {url = "/issue-161/", name = "Friends"},
]
