base_url = "https://jianghaiyina.com/"
theme = "float"
taxonomies = [
    {name = "categories", feeds = true},
    {name = "tags", feeds = true},
]
[extra]
even_title = "jaaleng's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/top/", name = "Top"},
    {url = "$BASE_URL/tags/", name = "Tags"},
    {url = "$BASE_URL/issue-1/", name = "About"},
    {url = "$BASE_URL/issue-161/", name = "Friends"},
]
